[package]
name = "aoc2023"
version = "0.1.0"
authors = ["Molive <moliveofscratch@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.18"
time = "*"
